Added option to skip sketch animations
quackbarc/garyc-sketch-tweaks pull request #1
Opened 2022-10-21 20:53 UTC by Diamondtroller

Added an option in preferences to skip sketch animations. By enabling this, space button can be used to (re)play sketch animation.

2022-10-26 14:32 UTC, quackbarc requested changes
Added comments on some of the changes here, but I wanna suggest some other stuff that should be added in as well:

* `_getSetting()` has an object for default settings and should be updated for the new setting:
https://github.com/quackbarc/garyc-sketch-tweaks/blob/e999b4e3be66213e02b9c52a5a46fe728f33b178/sketch.user.js#L35-L39

* The gallery viewer's click handler should also have the re-animating functionality, not just hitting `space`:
https://github.com/quackbarc/garyc-sketch-tweaks/blob/e999b4e3be66213e02b9c52a5a46fe728f33b178/sketch.user.js#L195

2022-10-26 14:32 UTC, quackbarc commented on README.md
> +* Added option to skip sketch animation
I think this could go under "Features", with a different wording to fit the other lines:
```suggestion
* Toggleable auto-skipping of sketch animations.
```

I'd also label these as "auto-skipping" instead of just "skipping" so it doesn't get confused with the normal skipping sketch already could do.

2022-10-26 14:32 UTC, quackbarc commented on sketch.user.js
> +            <label for="skipanimation">Skip sketch animation:</label>
```suggestion
            <label for="skipanimation">Auto-skip sketch animation:</label>
```

2022-10-27 17:09 UTC, Diamondtroller commented
>The gallery viewer's click handler should also have the re-animating functionality, not just hitting `space`

I kept skipping on click because there should still exist a way to skip sketches, while animation is playing. Removing click would limit user to either closing sketch and reopening it or go to neighbouring sketch and back to skip animation.

2022-10-27 19:11 UTC, quackbarc commented
Oh yeah good point, think I had trouble thinking on what to do about that when I did the same thing a bit back.

Thinking about it now though, I'm getting a couple ideas, so lemme know what you think about em:
1. We turn the `click` handler to toggle between animating the sketch and keeping it still instead of doing just one of them (`autodrawpos` could be used to tell if a sketch animating or not).
2. We keep the `space` handler to just keep the sketch still, but have another related keybind to re-animate the sketch (maybe `shift`+`space`? not sure if that'd clash into anything). The `noAnimation` setting shouldn't affect this.

Having 2. for the `click` handler I think would be pretty finicky, and having 1. for the `space` handler would kinda throw me off whenever I do some hasty sketch dumping.

2022-10-29 09:36 UTC, quackbarc requested changes
I still feel like the README addition and preference text could be worded better, but I think I could handle that myself.

Looks good so far, although one lil typo:

2022-10-29 09:36 UTC, quackbarc commented on sketch.user.js
> +    $("#doreplay").prop("checked", settings.noAnimation);
```suggestion
    $("#doreplay").prop("checked", settings.doReplay);
```

2022-10-29 18:45 UTC, quackbarc approved these changes

2022-10-29 18:47 UTC, quackbarc commented
Looks good to me, thanks!

2022-10-29 18:51 UTC, merged